[build]
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.51"
  HUGO_ENABLEGITINFO = "true"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[context.production.environment]
  HUGO_ENV = "production"