[build] 
  publish = "public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[context.production.environment]
  HUGO_VERSION = "0.60.1" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"