---
title: Key Commands about Git and GitHub Shell
author: Yuan Tian
date: '2017-12-21'
tags:
  - Git
  - tips
  - notes
slug: tips-about-git
---

Thanks to the [Step-by-Step Instruction provided by ALISON PRESMANES HILL](https://alison.rbind.io/post/up-and-running-with-blogdown/) and  ["Blogdown: Creating Websites with R Markdown"](https://bookdown.org/yihui/blogdown/), I was able to create this website. 
The repository of this website is kept on Git. When I tried to get refreshed on the common Git commands, I came across this wonderful [Guide to Git Shell](http://dh.newtfire.org/explainGitShell.html). This post is merely a note on the key common Git commands and core workflow in Git Shell (although you can complete all these actions via Git Desktop without interfering with the Shell).

**Two basic commands: `git pull` and `git push`.** The **`git pull`** can be divided into **`git fetch`** and **`git merge`**. 

Assuming you already have the repo on your local machine, then **a common workflow** will have 4 steps:

1. You **`ALWAYS`** need to be sure your local repo is up-to-date with the remote repo. 

```
#Make sure there are no untracked files.
git status 

#Pull in all the files changed on the remote
git fetch

#Comfirm that all the files are ready to merge
git status

#A final step in pulling the remote changes into local machine
git merge

#A final "git status" to confirm everything is good to go
git status
```
2. With some modifications/changes in your working directory, it is time to inform Git about your new changes using **`git add -A`**.

```
#Stage all the changed or newly added files in the working directory
git add -A

#Confirm again.
git status
```

3. It's time to **`git commit -m`**!

```
git commit -m "this is my commit"

#Confirm again
git status
```

4. The final **`git push`** to the remote repository.

```
git push

# Confirm everything is up-to-date
git status
```

Other commands that might be useful include: **`git branch --list`**, **`git help`**, etc. More can be found in the [Guide to Git Shell](http://dh.newtfire.org/explainGitShell.html) with illustrative figures and tutorials.
